on: [push]
jobs:
  run_tes_workflow:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            os_version: 0
            hardened: false
          #- os: macos-14
          #  os_version: 0
          #  hardened: false
#          - os: windows-latest
#            os_version: 0
#            hardened: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.13
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@v0.3
        with:
          tag: 'v25.1.0'
          hardened: ${{ matrix.hardened }}
          os_version_override: ${{ matrix.os_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Try to run E+ with full path
        run: ${{ steps.eplus.outputs.energyplus_directory }}/energyplus -D ${{ steps.eplus.outputs.energyplus_directory }}/ExampleFiles/1ZoneUncontrolled.idf
      - name: Install API Helper
        run: pip install -r requirements.txt
      - name: Try to run E+ from API
        run: python main.py ${{ steps.eplus.outputs.energyplus_directory }}
      - name: Upload baseline.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline
          path: baseline.zip
      - name: Upload secondary.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline
          path: secondary.zip